import type { Lang, ResourceCategory } from "./resourceItems";

const item = (name: string, url: string, fr: string, en: string, es: string, de: string, it: string, ja: string, sw: string) => ({
  name, url: `https://${url}`, desc: { fr, en, es, de, it, ja, sw } satisfies Record<Lang, string>,
});

export const exploreCategories: ResourceCategory[] = [
  { key: "live", items: [
    item("Zoom Earth", "zoom.earth", "Images satellite et météo en direct.", "Live satellite imagery and weather.", "Imágenes satelitales y tiempo en directo.", "Live-Satellitenbilder und Wetter.", "Immagini satellitari e meteo in diretta.", "衛星画像と気象をリアルタイムで。", "Picha za satelaiti na hali ya hewa moja kwa moja."),
    item("Flightradar24", "flightradar24.com", "Suivez les avions en vol.", "Track aircraft in flight.", "Sigue aviones en vuelo.", "Flugzeuge im Flug verfolgen.", "Segui gli aerei in volo.", "飛行中の航空機を追跡。", "Fuatilia ndege angani."),
    item("MarineTraffic", "marinetraffic.com", "Suivez les navires en mer.", "Track ships at sea.", "Sigue barcos en el mar.", "Schiffe auf See verfolgen.", "Segui le navi in mare.", "海上の船を追跡。", "Fuatilia meli baharini."),
    item("Windy", "windy.com", "Cartes des vents et des tempêtes.", "Wind and storm maps.", "Mapas de vientos y tormentas.", "Wind- und Sturmkarten.", "Mappe di venti e tempeste.", "風と嵐の地図。", "Ramani za upepo na dhoruba."),
    item("LightningMaps", "lightningmaps.org", "Observez les impacts de foudre.", "Watch lightning strikes.", "Observa impactos de rayos.", "Blitzeinschläge beobachten.", "Osserva i fulmini.", "落雷を観測。", "Tazama radi zinapopiga."),
    item("USGS Earthquakes", "earthquake.usgs.gov", "Consultez les séismes récents.", "Browse recent earthquakes.", "Consulta terremotos recientes.", "Aktuelle Erdbeben ansehen.", "Consulta i terremoti recenti.", "最近の地震を確認。", "Tazama matetemeko ya hivi karibuni."),
    item("Global Forest Watch", "globalforestwatch.org", "Suivez l’évolution des forêts.", "Monitor changes in forests.", "Sigue los cambios en los bosques.", "Veränderungen der Wälder verfolgen.", "Monitora i cambiamenti delle foreste.", "森林の変化を観察。", "Fuatilia mabadiliko ya misitu."),
  ]},
  { key: "maps", items: [
    item("Submarine Cable Map", "submarinecablemap.com", "Découvrez les câbles sous-marins d’Internet.", "Explore the internet’s undersea cables.", "Explora los cables submarinos de Internet.", "Internets Unterseekabel entdecken.", "Esplora i cavi sottomarini di Internet.", "インターネットの海底ケーブルを探索。", "Gundua nyaya za intaneti chini ya bahari."),
    item("The True Size", "thetruesize.com", "Comparez la taille réelle des pays.", "Compare countries’ true sizes.", "Compara el tamaño real de países.", "Die tatsächliche Größe von Ländern vergleichen.", "Confronta le dimensioni reali dei paesi.", "国の実際の大きさを比較。", "Linganisha ukubwa halisi wa nchi."),
    item("Old Maps Online", "oldmapsonline.org", "Explorez des cartes anciennes.", "Explore historical maps.", "Explora mapas históricos.", "Historische Karten erkunden.", "Esplora mappe storiche.", "歴史的な地図を探索。", "Chunguza ramani za kale."),
    item("David Rumsey", "davidrumsey.com", "Une collection de cartes historiques.", "A collection of historical maps.", "Una colección de mapas históricos.", "Eine Sammlung historischer Karten.", "Una raccolta di mappe storiche.", "歴史地図のコレクション。", "Mkusanyo wa ramani za kihistoria."),
    item("OpenStreetMap", "openstreetmap.org", "La carte collaborative du monde.", "The collaborative world map.", "El mapa colaborativo del mundo.", "Die gemeinschaftliche Weltkarte.", "La mappa collaborativa del mondo.", "共同制作の世界地図。", "Ramani ya dunia ya ushirikiano."),
  ]},
  { key: "travel", items: [
    item("WindowSwap", "window-swap.com", "Une fenêtre ouverte ailleurs dans le monde.", "A window into somewhere else in the world.", "Una ventana a otro lugar del mundo.", "Ein Fenster zu einem anderen Ort der Welt.", "Una finestra su un altro luogo del mondo.", "世界のどこかの窓からの眺め。", "Dirisha kuelekea sehemu nyingine duniani."),
    item("Virtual Vacation", "virtualvacation.us", "Promenez-vous virtuellement dans des villes.", "Take virtual walks through cities.", "Pasea virtualmente por ciudades.", "Virtuelle Spaziergänge durch Städte.", "Passeggia virtualmente nelle città.", "街をバーチャル散歩。", "Tembea mijini kwa njia pepe."),
    item("MapCrunch", "mapcrunch.com", "Découvrez un lieu aléatoire sur Terre.", "Discover a random place on Earth.", "Descubre un lugar aleatorio de la Tierra.", "Einen zufälligen Ort auf der Erde entdecken.", "Scopri un luogo casuale sulla Terra.", "地球上のランダムな場所を発見。", "Gundua sehemu ya bahati nasibu duniani."),
    item("Atlas Obscura", "atlasobscura.com", "Des lieux insolites à découvrir.", "Discover unusual places.", "Descubre lugares insólitos.", "Ungewöhnliche Orte entdecken.", "Scopri luoghi insoliti.", "珍しい場所を発見。", "Gundua maeneo yasiyo ya kawaida."),
  ]},
  { key: "space", items: [
    item("Neal.fun", "neal.fun", "Des expériences interactives pour les curieux.", "Interactive experiences for curious minds.", "Experiencias interactivas para curiosos.", "Interaktive Erlebnisse für Neugierige.", "Esperienze interattive per curiosi.", "好奇心を刺激する体験。", "Uzoefu shirikishi kwa wadadisi."),
    item("The Scale of the Universe", "htwins.net/scale2/", "Voyagez de l’atome à l’Univers.", "Journey from atoms to the universe.", "Viaja del átomo al universo.", "Vom Atom zum Universum reisen.", "Viaggia dall’atomo all’universo.", "原子から宇宙までの旅。", "Safiri kutoka atomu hadi ulimwengu."),
    item("NASA Eyes", "eyes.nasa.gov", "Explorez le système solaire en 3D.", "Explore the solar system in 3D.", "Explora el sistema solar en 3D.", "Das Sonnensystem in 3D erkunden.", "Esplora il sistema solare in 3D.", "太陽系を3Dで探索。", "Chunguza mfumo wa jua katika 3D."),
    item("Stellarium Web", "stellarium-web.org", "La carte du ciel dans votre navigateur.", "A sky map in your browser.", "Un mapa del cielo en tu navegador.", "Eine Himmelskarte im Browser.", "Una mappa del cielo nel browser.", "ブラウザで星空地図を。", "Ramani ya anga kwenye kivinjari."),
    item("NASA APOD", "apod.nasa.gov", "Une image d’astronomie chaque jour.", "An astronomy picture every day.", "Una imagen astronómica cada día.", "Jeden Tag ein Astronomiebild.", "Un’immagine astronomica ogni giorno.", "毎日の天文写真。", "Picha ya astronomia kila siku."),
    item("NASA Images", "images.nasa.gov", "Explorez les archives visuelles de la NASA.", "Explore NASA’s visual archives.", "Explora el archivo visual de NASA.", "Das Bildarchiv der NASA erkunden.", "Esplora gli archivi visivi della NASA.", "NASAの画像アーカイブを探索。", "Chunguza nyaraka za picha za NASA."),
  ]},
  { key: "data", items: [
    item("Worldometer", "worldometers.info", "Statistiques mondiales et compteurs.", "World statistics and counters.", "Estadísticas mundiales y contadores.", "Weltweite Statistiken und Zähler.", "Statistiche mondiali e contatori.", "世界の統計とカウンター。", "Takwimu za dunia na vihesabu."),
    item("Internet Live Stats", "internetlivestats.com", "Des chiffres sur l’activité d’Internet.", "Statistics about internet activity.", "Estadísticas de actividad de Internet.", "Statistiken zur Internetaktivität.", "Statistiche sull’attività di Internet.", "インターネット活動の統計。", "Takwimu za shughuli za intaneti."),
    item("The Pudding", "pudding.cool", "Des histoires racontées par les données.", "Stories told through data.", "Historias contadas con datos.", "Geschichten durch Daten erzählt.", "Storie raccontate con i dati.", "データで語る物語。", "Hadithi zinazosimuliwa kwa data."),
    item("Our World in Data", "ourworldindata.org", "Comprenez le monde grâce aux données.", "Understand the world through data.", "Comprende el mundo con datos.", "Die Welt durch Daten verstehen.", "Comprendi il mondo attraverso i dati.", "データを通して世界を理解。", "Elewa dunia kupitia data."),
    item("Gapminder", "gapminder.org", "Testez vos idées reçues sur le monde.", "Challenge your assumptions about the world.", "Cuestiona tus ideas sobre el mundo.", "Vorstellungen über die Welt hinterfragen.", "Metti alla prova le tue idee sul mondo.", "世界についての思い込みを検証。", "Pima dhana zako kuhusu dunia."),
    item("Information is Beautiful", "informationisbeautiful.net", "Des données complexes rendues visuelles.", "Complex data made visual.", "Datos complejos en imágenes.", "Komplexe Daten visualisiert.", "Dati complessi resi visivi.", "複雑なデータを視覚化。", "Data changamano kwa picha."),
    item("World Bank Open Data", "data.worldbank.org", "Données ouvertes de la Banque mondiale.", "World Bank open data.", "Datos abiertos del Banco Mundial.", "Offene Daten der Weltbank.", "Dati aperti della Banca Mondiale.", "世界銀行のオープンデータ。", "Data wazi za Benki ya Dunia."),
    item("TÜİK Data", "data.tuik.gov.tr", "Statistiques officielles de la Turquie.", "Turkey’s official statistics.", "Estadísticas oficiales de Turquía.", "Offizielle Statistiken der Türkei.", "Statistiche ufficiali della Turchia.", "トルコの公式統計。", "Takwimu rasmi za Uturuki."),
    item("Observable", "observablehq.com", "Visualisez des données avec du code interactif.", "Visualize data with interactive code.", "Visualiza datos con código interactivo.", "Daten mit interaktivem Code visualisieren.", "Visualizza dati con codice interattivo.", "対話型コードでデータを視覚化。", "Onyesha data kwa msimbo shirikishi."),
  ]},
  { key: "culture", items: [
    item("Internet Archive", "archive.org", "Livres, films et logiciels archivés.", "Archived books, films and software.", "Libros, películas y software archivados.", "Archivierte Bücher, Filme und Software.", "Libri, film e software archiviati.", "書籍・映画・ソフトウェアのアーカイブ。", "Vitabu, filamu na programu zilizohifadhiwa."),
    item("Project Gutenberg", "gutenberg.org", "Des livres du domaine public gratuits.", "Free public-domain books.", "Libros gratuitos de dominio público.", "Kostenlose gemeinfreie Bücher.", "Libri gratuiti di pubblico dominio.", "無料のパブリックドメイン書籍。", "Vitabu vya bure vya umma."),
    item("Open Library", "openlibrary.org", "Explorez un vaste catalogue de livres.", "Explore a vast book catalogue.", "Explora un amplio catálogo de libros.", "Einen umfangreichen Buchkatalog erkunden.", "Esplora un vasto catalogo di libri.", "広大な書籍カタログを探索。", "Chunguza orodha kubwa ya vitabu."),
    item("Library of Congress", "loc.gov", "Collections numériques de la bibliothèque américaine.", "Digital collections of the US national library.", "Colecciones digitales de la biblioteca estadounidense.", "Digitale Sammlungen der US-Nationalbibliothek.", "Collezioni digitali della biblioteca nazionale americana.", "米国議会図書館のデジタル資料。", "Makusanyo ya kidijitali ya maktaba ya Marekani."),
    item("Europeana", "europeana.eu", "Explorez le patrimoine culturel européen.", "Explore Europe’s cultural heritage.", "Explora el patrimonio cultural europeo.", "Europas Kulturerbe erkunden.", "Esplora il patrimonio culturale europeo.", "欧州の文化遺産を探索。", "Chunguza urithi wa utamaduni wa Ulaya."),
    item("Digital Public Library of America", "dp.la", "Collections numériques des bibliothèques américaines.", "Digital collections from American libraries.", "Colecciones digitales de bibliotecas estadounidenses.", "Digitale Sammlungen amerikanischer Bibliotheken.", "Collezioni digitali delle biblioteche americane.", "米国図書館のデジタルコレクション。", "Makusanyo ya kidijitali ya maktaba za Marekani."),
    item("Google Arts & Culture", "artsandculture.google.com", "Visitez des musées depuis chez vous.", "Visit museums from home.", "Visita museos desde casa.", "Museen von zu Hause besuchen.", "Visita musei da casa.", "自宅から美術館を訪問。", "Tembelea makumbusho ukiwa nyumbani."),
    item("Rijksmuseum", "rijksmuseum.nl", "Admirez les œuvres en haute résolution.", "View artworks in high resolution.", "Admira obras en alta resolución.", "Kunstwerke in hoher Auflösung ansehen.", "Ammira opere in alta risoluzione.", "高解像度の美術作品を鑑賞。", "Tazama sanaa kwa ubora wa juu."),
    item("WikiArt", "wikiart.org", "Une vaste encyclopédie des arts visuels.", "A vast visual arts encyclopedia.", "Una amplia enciclopedia de artes visuales.", "Eine große Enzyklopädie der bildenden Kunst.", "Una vasta enciclopedia delle arti visive.", "広大な視覚芸術の百科事典。", "Ensaiklopidia kubwa ya sanaa za kuona."),
    item("The Public Domain Review", "publicdomainreview.org", "Trésors oubliés de l’histoire et de l’art.", "Forgotten treasures of history and art.", "Tesoros olvidados de historia y arte.", "Vergessene Schätze aus Geschichte und Kunst.", "Tesori dimenticati di storia e arte.", "歴史と芸術の忘れられた宝物。", "Hazina zilizosahaulika za historia na sanaa."),
    item("Open Culture", "openculture.com", "Culture et apprentissage en libre accès.", "Freely accessible culture and learning.", "Cultura y aprendizaje de libre acceso.", "Frei zugängliche Kultur und Bildung.", "Cultura e apprendimento ad accesso libero.", "自由にアクセスできる文化と学習。", "Utamaduni na elimu zinazopatikana bure."),
    item("The Met", "metmuseum.org", "Découvrez les collections du Metropolitan Museum.", "Discover the Metropolitan Museum collections.", "Descubre las colecciones del Metropolitan Museum.", "Die Sammlungen des Metropolitan Museum entdecken.", "Scopri le collezioni del Metropolitan Museum.", "メトロポリタン美術館のコレクション。", "Gundua makusanyo ya Metropolitan Museum."),
  ]},
  { key: "sound", items: [
    item("Musicmap", "musicmap.info", "Explorez les liens entre les genres musicaux.", "Explore connections between music genres.", "Explora conexiones entre géneros musicales.", "Verbindungen zwischen Musikgenres erkunden.", "Esplora i legami tra generi musicali.", "音楽ジャンルのつながりを探索。", "Chunguza uhusiano kati ya aina za muziki."),
    item("Radiooooo", "radiooooo.com", "Choisissez un pays et une décennie musicale.", "Choose a country and a musical decade.", "Elige un país y una década musical.", "Ein Land und ein Musikjahrzehnt wählen.", "Scegli un paese e un decennio musicale.", "国と年代を選んで音楽を聴く。", "Chagua nchi na muongo wa muziki."),
    item("Listen to Wikipedia", "listen.hatnote.com", "Écoutez les modifications de Wikipédia.", "Listen to Wikipedia edits.", "Escucha las ediciones de Wikipedia.", "Wikipedia-Bearbeitungen hören.", "Ascolta le modifiche di Wikipedia.", "ウィキペディアの編集を音で聴く。", "Sikiliza mabadiliko ya Wikipedia."),
  ]},
  { key: "knowledge", items: [
    item("Wikipedia", "wikipedia.org", "Explorez l’encyclopédie collaborative.", "Explore the collaborative encyclopedia.", "Explora la enciclopedia colaborativa.", "Die gemeinschaftliche Enzyklopädie erkunden.", "Esplora l’enciclopedia collaborativa.", "共同編集の百科事典を探索。", "Chunguza ensaiklopidia ya ushirikiano."),
    item("Time and Date", "timeanddate.com", "Heures, levers du soleil et événements célestes.", "Time, sunrises and celestial events.", "Horas, amaneceres y eventos celestes.", "Uhrzeiten, Sonnenaufgänge und Himmelsereignisse.", "Orari, albe ed eventi celesti.", "時刻・日の出・天文イベント。", "Saa, macheo na matukio ya angani."),
    item("ScienceDaily", "sciencedaily.com", "Les dernières nouvelles scientifiques.", "The latest science news.", "Las últimas noticias científicas.", "Die neuesten Wissenschaftsnachrichten.", "Le ultime notizie scientifiche.", "最新の科学ニュース。", "Habari mpya za sayansi."),
    item("arXiv", "arxiv.org", "Consultez des prépublications scientifiques.", "Browse scientific preprints.", "Consulta prepublicaciones científicas.", "Wissenschaftliche Preprints lesen.", "Consulta prepubblicazioni scientifiche.", "科学論文のプレプリントを閲覧。", "Soma machapisho ya awali ya kisayansi."),
  ]},
];